# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'/Users/nirvanapersaud/Downloads/GymSwift/GymSwift/Podfile

target 'GymSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Parse'
  pod 'AlamofireImage'
  pod 'lottie-ios'

  # Pods for GymSwift

  pod 'TTGTagCollectionView'

end
